import { StyleSheet } from 'react-native';
import { ThemeType } from './theme';

const createStyles = (theme: ThemeType) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
      paddingHorizontal: 20,
      paddingTop: 40,
    },
    container: {
      flex: 1,
      paddingHorizontal: 20,
      backgroundColor: theme.background,
      justifyContent: 'flex-start',
    },
    header: {
      fontSize: 32,
      fontWeight: '900',
      marginBottom: 24,
      textAlign: 'center',
      color: theme.primary,
      textShadowColor: '#FF0000',
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 12,
    },
    search: {
      height: 50,
      borderWidth: 2,
      borderColor: theme.primary,
      borderRadius: 12,
      paddingHorizontal: 18,
      marginBottom: 20,
      fontSize: 18,
      color: theme.text,
      backgroundColor: '#111',
      shadowColor: '#FF0000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 10,
      elevation: 10,
    },
    card: {
      padding: 20,
      borderRadius: 16,
      marginBottom: 20,
      backgroundColor: '#1a1a1a',
      borderColor: theme.primary,
      borderWidth: 1.5,
      shadowColor: '#FF0000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 12,
      elevation: 15,
    },
    title: {
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 8,
      color: theme.primary,
      textShadowColor: '#FF0000',
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 8,
    },
    info: {
      fontSize: 16,
      marginBottom: 6,
      color: theme.text,
    },
    description: {
      fontSize: 14,
      marginTop: 8,
      color: '#ccc',
      fontStyle: 'italic',
    },
    buttonContainer: {
      flexDirection: 'row',
      marginTop: 16,
      justifyContent: 'space-between',
    },
    button: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      marginHorizontal: 6,
      backgroundColor: theme.primary,
      shadowColor: '#FF0000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 10,
      elevation: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonText: {
      color: '#fff',
      fontWeight: 'bold',
      fontSize: 16,
      textShadowColor: '#ff4d4d',
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 8,
    },
    noItemsContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    noItemsText: {
      fontSize: 18,
      color: '#ff4d4d',
      textAlign: 'center',
      fontWeight: '600',
      textShadowColor: '#ff0000',
      textShadowRadius: 10,
    },
    refreshButton: {
      paddingVertical: 14,
      paddingHorizontal: 30,
      borderRadius: 12,
      backgroundColor: theme.primary,
      shadowColor: '#FF0000',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 10,
      elevation: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 20,
    },
    input: {
      backgroundColor: '#222',
      borderRadius: 10,
      paddingHorizontal: 18,
      paddingVertical: 14,
      marginBottom: 20,
      fontSize: 18,
      color: '#fff', // white text for visibility
      shadowColor: '#FF0000',
      shadowOpacity: 0.9,
      shadowRadius: 10,
      elevation: 10,
    },
    errorText: {
      color: '#ff4d4d',
      marginBottom: 20,
      fontWeight: '700',
      textAlign: 'center',
      textShadowColor: '#ff0000',
      textShadowRadius: 8,
    },

    buttonCenteredContainer: {
      width: '80%',
      alignSelf: 'center',
      marginVertical: 8,
    },
  });

export default createStyles;
